### ISSUE TITLE
Fail to unzip when specifying version latest

### ISSUE THREAD

**Issue by andr3a88** [xavierLowmiller/xcodegen-action#5]
When is specified version `latest` the actions fail to unzip the package

```
  with:
    spec: project.yml
    quiet: true
    version: latest
```

the url does not exists

`https://github.com/yonaskolb/XcodeGen/releases/download/latest/xcodegen.zip`
